FROM ubuntu:jammy-20220531@sha256:bace9fb0d5923a675c894d5c815da75ffe35e24970166a48a4460a48ae6e0d19

RUN apt update \
    && apt install libboost-python-dev=1.74.0.3ubuntu7 \
                   build-essential=12.9ubuntu3 \
                   python3-build=0.7.0-2 \
                   python3-pip=22.0.2+dfsg-1 \
                   python3-venv=3.10.4-0ubuntu2 \
                   python-setuptools=44.1.1-1.2 \
                   python-is-python3 \
                   git \
                   -y \
    && apt clean

CMD /bin/bash
